# recipe: xfce4 minimal installation
# author: artisan
---

type: "recipe"
name: "xfce4-minimal-installation"
applyTo: "naked"
author: "artisan"
release: "20220311"

- ingredients
  # debs
  - operation: sources.list
  # operation: sources.list.d
  - operation: coock
  - end

# Descrive the ...
- sources.list
  - contrib
  - non-free

# sources.list.d (example)
 # command: curl https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
 # command: echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" > ~/waydroid.list
 # command: mv ~/waydroid.list /etc/apt/sources.list.d/waydroid.list

- coock
  - command: apt-get update
  - command: apt-get upgrade
  - command: apt-get install -y \
    libxfce4ui-utils \
    thunar \
    xfce4-appfinder \
    xfce4-panel \
    xfce4-pulseaudio-plugin \
    xfce4-whiskermenu-plugin \
    xfce4-session \
    xfce4-settings \
    xfce4-terminal \
    xfconf \
    xfdesktop4 \
    xfwm4 \
    adwaita-qt \
    qt5ct 
  - command: apt-get install network-manager-openvpn \
    network-manager-gnome \
    network-manager-openvpn-gnome

# debs (example)
  # command: dpkg -i *.deb