services:
    - name: bluetooth
      mandatory: false

    - name: ModemManager
      mandatory: false

    - name: NetworkManager
      mandatory: false

    - name: cups
      mandatory: false

    - name: haveged
      mandatory: false

    - name: ufw
      mandatory: false

    - name: apparmor
      mandatory: false

    - name: snapd.apparmor
      mandatory: false

    - name: snapd
      mandatory: false

    - name: fstrim.timer
      mandatory: false

    - name: pkgfile–update.timer
      mandatory: false

    - name: touchegg.service
      mandatory: false

    - name: btrfs-balance.timer
      mandatory: false

    - name: btrfs-scrub.timer
      mandatory: false

    - name: btrfs-trim.timer
      mandatory: false

    - name: gdm
      mandatory: false

targets:
    - name: "graphical"
      mandatory: true

disable:
    - name: pacman-init
      mandatory: false

